[package]
name = "sp-mvm"
authors = ["Pontem Network Team <https://pontem.network>"]
description = "FRAME pallet adding Move-lang support."
edition = "2018"
repository = "https://github.com/pontem-network/sp-move"
version = "0.2.1"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]


[dependencies.log]
version = "0.4"
default-features = false

[dependencies.codec]
version = "2.0.0"
default-features = false
features = ["derive"]
package = "parity-scale-codec"


# Move, addition deps for addrs & results:

[dependencies.move-vm]
package = "mvm"
git = "https://github.com/pontem-network/sp-move-vm.git"
branch = "milestone-3"
default-features = false

[dependencies.vm]
git = "https://github.com/pontem-network/sp-move-vm.git"
branch = "milestone-3"
default-features = false

[dependencies.move-vm-runtime]
git = "https://github.com/pontem-network/sp-move-vm.git"
branch = "milestone-3"
default-features = false

[dependencies.move-core-types]
git = "https://github.com/pontem-network/sp-move-vm.git"
branch = "milestone-3"
default-features = false

[dependencies.move-vm-types]
git = "https://github.com/pontem-network/sp-move-vm.git"
branch = "milestone-3"
default-features = false

[dev-dependencies.lcs]
package = "bcs"
default-features = false
git = "https://github.com/pontem-network/sp-move-vm.git"
branch = "milestone-3"

[dependencies]
once_cell = { default-features = false, version = "1.5.2" }
# substrate:
frame-support = { default-features = false, version = "3.0.0" }
frame-system = { default-features = false, version = "3.0.0" }
# frame-benchmarking = { default-features = false, optional = true, version = '3.1.0' }
# corelib, std, structs:
sp-std = { default-features = false, version = "3.0.0" }
sp-core = { default-features = false, version = "3.0.0" }
# calc timestamp for block:
timestamp = { default-features = false, version = "3.0.0", package = "pallet-timestamp" }
# logging, `sp_runtime::print`:
sp-runtime = { default-features = false, version = "3.0.0" }


[dev-dependencies]
sp-io = { default-features = false, version = "3.0.0" }
# serde is for lcs only
serde = { version = "1", default-features = false, package = "alt_serde", features = ["derive", "alloc"] }


[features]
default = [ "std" ]
std = [
    "log/std",
    "once_cell/std",
    "vm/std",
    "move-vm/std",
    "move-vm-runtime/std",
    "move-core-types/std",
    "sp-std/std",
    "sp-core/std",
    "sp-runtime/std",
    "codec/std",
    "frame-support/std",
    "frame-system/std",
    # "frame-benchmarking/std",
    "move-vm-types/std",
    # dev deps:
    "lcs/std",
    "serde/std",
    "sp-io/std",
]

# runtime-benchmarks = [ "frame-benchmarking" ]

# Note: frame-support `try-runtime` feature is released after v3.
# Uncomment the following line when `frame-support` version > `3.0.0`.
# try-runtime = ['frame-support/try-runtime']
