[package]
name = "sp-mvm-rpc-runtime"
authors = [ "Pontem Network Team <https://pontem.network>" ]
description = "Runtime RPC for Move pallet."
edition = "2018"
repository = "https://github.com/pontem-network/sp-move"
version = "0.2.2"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-api = { default-features = false, version = '3.0.0' }
frame-support = { default-features = false, version = "3.0.0" }

[features]
default = ["std"]
std = [
	"sp-api/std",
	"frame-support/std",
]
